name: Publish CI

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.18.0'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@hcm4all'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn publish --access restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}